sudo: required

language: bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y git build-essential

script:
  - git clone https://github.com/torvalds/linux.git --depth=1 --branch=v4.7
  - cp * linux && cd linux && ./setup.sh && ./boot.sh
